In [1]:
import pandas as pd

In [2]:
with open('D10.txt') as f:
    raw_lines = f.readlines()

lines = []
for line in raw_lines:
    lines.append(line.strip())

lines = ['addx 15',
'addx -11',
'addx 6',
'addx -3',
'addx 5',
'addx -1',
'addx -8',
'addx 13',
'addx 4',
'noop',
'addx -1',
'addx 5',
'addx -1',
'addx 5',
'addx -1',
'addx 5',
'addx -1',
'addx 5',
'addx -1',
'addx -35',
'addx 1',
'addx 24',
'addx -19',
'addx 1',
'addx 16',
'addx -11',
'noop',
'noop',
'addx 21',
'addx -15',
'noop',
'noop',
'addx -3',
'addx 9',
'addx 1',
'addx -3',
'addx 8',
'addx 1',
'addx 5',
'noop',
'noop',
'noop',
'noop',
'noop',
'addx -36',
'noop',
'addx 1',
'addx 7',
'noop',
'noop',
'noop',
'addx 2',
'addx 6',
'noop',
'noop',
'noop',
'noop',
'noop',
'addx 1',
'noop',
'noop',
'addx 7',
'addx 1',
'noop',
'addx -13',
'addx 13',
'addx 7',
'noop',
'addx 1',
'addx -33',
'noop',
'noop',
'noop',
'addx 2',
'noop',
'noop',
'noop',
'addx 8',
'noop',
'addx -1',
'addx 2',
'addx 1',
'noop',
'addx 17',
'addx -9',
'addx 1',
'addx 1',
'addx -3',
'addx 11',
'noop',
'noop',
'addx 1',
'noop',
'addx 1',
'noop',
'noop',
'addx -13',
'addx -19',
'addx 1',
'addx 3',
'addx 26',
'addx -30',
'addx 12',
'addx -1',
'addx 3',
'addx 1',
'noop',
'noop',
'noop',
'addx -9',
'addx 18',
'addx 1',
'addx 2',
'noop',
'noop',
'addx 9',
'noop',
'noop',
'noop',
'addx -1',
'addx 2',
'addx -37',
'addx 1',
'addx 3',
'noop',
'addx 15',
'addx -21',
'addx 22',
'addx -6',
'addx 1',
'noop',
'addx 2',
'addx 1',
'noop',
'addx -10',
'noop',
'noop',
'addx 20',
'addx 1',
'addx 2',
'addx 2',
'addx -6',
'addx -11',
'noop',
'noop',
'noop']

In [3]:
expanded_lines = []
for line in lines:
    if line[0:4] == 'addx':
        expanded_lines.append('addx 0')
        expanded_lines.append(line)
    else:
        expanded_lines.append(line)

In [4]:
xs = []
cycles = []
x = 1

for cycle in range(len(expanded_lines)):
    
    cycles.append(cycle+1)
    instruct = expanded_lines[cycle]
    
    if instruct == 'noop':
        pass
    
    elif instruct[0:4] == 'addx':
        x = x + int(instruct[5::])
    
    xs.append(x)

In [5]:
signal_strengths = [x * cycle for x, cycle in zip(xs[0:-1], cycles[1::])]

In [6]:
df = pd.DataFrame({'cycle': cycles[1::], 'x': xs[0:-1], 'signal strength': signal_strengths})
df.set_index('cycle', inplace=True)

In [7]:
sum(df.loc[[20, 60, 100, 140, 180, 220]]['signal strength'])

12640

In [8]:
def get_signal_cycle(cycles, df):
    
    sum_signals = 0
    
    for cycle in cycles:
        
        sum_signals += df.loc[cycle]['signal strength']
        
    return sum_signals

## Part 2

In [9]:
df

        x  signal strength
cycle
2       1                2
3       2                6
4       2                8
5       2               10
6       4               24
...    ..              ...
236    34             8024
237    34             8058
238    34             8092
239    37             8843
240    37             8880

[239 rows x 2 columns]

In [10]:
def get_sprite_position(cycle):
    
    if cycle == 1:
        sprite_position = '###.....................................'
    
    else:
        x = df.loc[cycle].x
        sprite_position_lst = list('........................................')
        sprite_position_lst[x-1:x+1] = '###'
        sprite_position = ''.join(sprite_position_lst)
    
    return sprite_position

In [11]:
sprite_position = '###.....................................'
pixel_position = 0

for i_start in range(0,len(df),40):
    
    CRT_row = ''

    for cycle in range(i_start+1, i_start+41):
        sprite_position = get_sprite_position(cycle)
        CRT_row += sprite_position[pixel_position-i_start]
        pixel_position+=1

    print(CRT_row)

####.#..#.###..####.#....###....##.###.#
.....#..#.#..#....#.#....#..#....#.#..##
.##..####.###....#..#....#..#....#.#..##
.....#..#.#..#..#...#....###.....#.###..
.....#..#.#..#.#....#....#.#..#..#.#.###
..##.#..#.###..####.####.#..#..##..#..#.